# Site settings
title: Anita's Brownies
email: anitasbrownies@anitasbrownies.com
description: "En ANITA´S BROWNIES hacemos los brownies más ricos de Colombia. Hechos con los mejores ingredientes, nuestros brownies han sido un delicioso placer por más de 25 años. Brownies de Maní, Chocolate, Integrales, con Arequipe y con Mantequilla de Maní, además de Mini-Brownies y Brownies decorados para ocasiones especiales, siempre deliciosos."

# Setup
baseurl: https://juanfrans.github.io/anitas-brownies/

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000000 #80B3FF
  secondary: 000000 #FD6E8A
  secondary-dark: 999999 #A2122F
  
# Footer settings
footer:
  copyright: Anita's Brownies
  location: Dirección
  telefnonos: Teléfonos
  social: Síguenos         

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://es-es.facebook.com/pages/Anitas-Brownies/242121495819009

# Postal address (add as many lines as necessary)
address:
  - line: Calle 4 no. 34 - 47
  - line: Cali - Colombia

# Telefonos
telefnonos:
  - line: Cali 556 4640
  - line: Bogota 860 6300
  - line: Bogota Cel. 321 200 4606

# Build settings
markdown: kramdown
permalink: pretty
